// ─────────────────────────────────────────────────────────────────────────────
// BUNDLER for the browser multiplayer transport.
//
// Bundles net/duke-net.ts + its imports + the three npm deps (nostr-tools,
// qrcode, jsqr) into ONE self-contained file, platform/emscripten/eduke32-net.js,
// that runs beside the Emscripten output (eduke32.js / .wasm / .data).
//
// This is a SEPARATE toolchain from `make`: it never enters the emcc graph. The
// Emscripten build produces eduke32.js; this produces eduke32-net.js; index.html
// loads both. (The tiny C<->JS seam that the wasm links, net/seam_library.js, is
// consumed by emcc via --js-library and is intentionally NOT bundled here.)
// ─────────────────────────────────────────────────────────────────────────────
import { build, context } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const watch = process.argv.includes("--watch");

/** @type {import('esbuild').BuildOptions} */
const options = {
  entryPoints: [resolve(__dirname, "net/duke-net.ts")],
  outfile: resolve(__dirname, "eduke32-net.js"),
  bundle: true,
  format: "esm", // loaded via <script type="module" src="eduke32-net.js">
  platform: "browser",
  target: ["es2020"],
  // Self-contained: every dep is inlined so the page needs no CDN / bare-import
  // resolution (the Artifact/Pages CSP and offline play both require this).
  external: [],
  minify: true,
  sourcemap: true,
  legalComments: "none",
  logLevel: "info",
  banner: {
    js: "/* eduke32-net.js — WebRTC+Nostr multiplayer transport for EDuke32-WASM. Generated by esbuild; edit net/*.ts and run `npm run build:net`. */",
  },
};

if (watch) {
  const ctx = await context(options);
  await ctx.watch();
  console.log("[build:net] watching net/*.ts …");
} else {
  await build(options);
  console.log("[build:net] wrote eduke32-net.js");
}
